version: '3.8'

services:
  localstack:
    container_name: localstack_security_system
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Edge Port
    environment:
      - SERVICES=s3,dynamodb,lambda,iam,ec2,sns,sqs,cloudtrail
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"
